// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlI1jpEssaN-aobp5aIAKT1ChA8nnTWe0',
    appId: '1:847301739878:web:6d7ab6540f6f05ad88f4a7',
    messagingSenderId: '847301739878',
    projectId: 'construction-be459',
    authDomain: 'construction-be459.firebaseapp.com',
    storageBucket: 'construction-be459.firebasestorage.app',
    measurementId: 'G-G8TFDCEET5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi8e9-en_zFa89vX3dmEQ6mCq-7ryHRhI',
    appId: '1:847301739878:android:531a094fe5e6be9688f4a7',
    messagingSenderId: '847301739878',
    projectId: 'construction-be459',
    storageBucket: 'construction-be459.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1nCp7IXQniSgvHypEN_2Dnf_WYAIiSus',
    appId: '1:847301739878:ios:0be4f556e0233b1b88f4a7',
    messagingSenderId: '847301739878',
    projectId: 'construction-be459',
    storageBucket: 'construction-be459.firebasestorage.app',
    iosBundleId: 'com.example.construction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1nCp7IXQniSgvHypEN_2Dnf_WYAIiSus',
    appId: '1:847301739878:ios:0be4f556e0233b1b88f4a7',
    messagingSenderId: '847301739878',
    projectId: 'construction-be459',
    storageBucket: 'construction-be459.firebasestorage.app',
    iosBundleId: 'com.example.construction',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlI1jpEssaN-aobp5aIAKT1ChA8nnTWe0',
    appId: '1:847301739878:web:8442c9baf3c22bb288f4a7',
    messagingSenderId: '847301739878',
    projectId: 'construction-be459',
    authDomain: 'construction-be459.firebaseapp.com',
    storageBucket: 'construction-be459.firebasestorage.app',
    measurementId: 'G-R8YJ6JNRM3',
  );
}
